DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`stef`@`%`*/ /*!50003 TRIGGER `tr_transdet_d` BEFORE DELETE ON `transdet` FOR EACH ROW begin
insert into transdet_audit (
	tran_id,
	tran_date,
	tran_creditor,
	tran_desc,
	tran_amount,
	cr_dr,
	tran_type_id,
	account_id,
	statement_date,
	cheque_no,
	receipt_ind,
	dd_ind,
	date_created,
	user_created,
	date_amended,
	user_amended,
	frequency,
	cred_id,
	branch_id,
	cost_code,
	crdd,
	brnd,
	booking,
	payment_type
) select 
	tran_id,
	tran_date,
	tran_creditor,
	tran_desc,
	tran_amount,
	cr_dr,
	tran_type_id,
	account_id,
	statement_date,
	cheque_no,
	receipt_ind,
	dd_ind,
	date_created,
	user_created,
	date_amended,
	user_amended,
	frequency,
	cred_id,
	branch_id,
	cost_code,
	crdd,
	brnd,
	booking,
	payment_type
from transdet where tran_id=old.tran_id;
end */;;
DELIMITER ;
